apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-volume-claim
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: jenkins-volume
  storageClassName: ""
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-master
  namespace: jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins-master
    spec:
      containers:
      - name: jenkins-master
        image: jenkins/jenkins:2.91-alpine
        ports:
        - containerPort: 8080
        - containerPort: 50000
        readinessProbe:
          httpGet:
            path: /login
            port: 8080
          periodSeconds: 30
          timeoutSeconds: 15
          successThreshold: 2
          failureThreshold: 5
        env:
          - name: JENKINS_OPTS
            valueFrom:
              secretKeyRef:
                name: jenkins
                key: options
          - name: JAVA_OPTS
            value: '-Xmx1500m -Xms1024m'
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-volume
        resources:
          limits:
            cpu: 500m
            memory: 1600Mi
          requests:
            cpu: 500m
            memory: 1600Mi
      volumes:
      - name: jenkins-volume
        persistentVolumeClaim:
          claimName: jenkins-volume-claim