apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "jenkins-volume-claim"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"
  volumeName: "jenkins-volume"